// <auto-generated />
using System;
using KeyloopScheduler.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KeyloopScheduler.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SchedulerDbContext))]
    partial class SchedulerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KeyloopScheduler.Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("cancelled_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DealershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("dealership_id");

                    b.Property<DateTime>("EndTimeUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("end_time_utc");

                    b.Property<Guid>("ServiceBayId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_bay_id");

                    b.Property<Guid>("ServiceTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_type_id");

                    b.Property<DateTime>("StartTimeUtc")
                        .HasColumnType("timestamptz")
                        .HasColumnName("start_time_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<Guid>("TechnicianId")
                        .HasColumnType("uuid")
                        .HasColumnName("technician_id");

                    b.Property<string>("VehicleIdentification")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)")
                        .HasColumnName("vin");

                    b.HasKey("Id");

                    b.HasIndex("ServiceTypeId");

                    b.HasIndex("DealershipId", "Status", "StartTimeUtc")
                        .HasDatabaseName("ix_appointments_dealership_status_start");

                    b.HasIndex("ServiceBayId", "StartTimeUtc", "EndTimeUtc")
                        .HasDatabaseName("ix_appointments_bay_window");

                    b.HasIndex("TechnicianId", "StartTimeUtc", "EndTimeUtc")
                        .HasDatabaseName("ix_appointments_technician_window");

                    b.ToTable("appointments", (string)null);
                });

            modelBuilder.Entity("KeyloopScheduler.Domain.Entities.Dealership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("dealerships", (string)null);
                });

            modelBuilder.Entity("KeyloopScheduler.Domain.Entities.ServiceBay", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DealershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("dealership_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("DealershipId", "IsActive")
                        .HasDatabaseName("ix_service_bays_dealership_active");

                    b.ToTable("service_bays", (string)null);
                });

            modelBuilder.Entity("KeyloopScheduler.Domain.Entities.ServiceType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("RequiredCertification")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("required_certification");

                    b.HasKey("Id");

                    b.ToTable("service_types", (string)null);
                });

            modelBuilder.Entity("KeyloopScheduler.Domain.Entities.Technician", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int[]>("Certifications")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("certifications");

                    b.Property<Guid>("DealershipId")
                        .HasColumnType("uuid")
                        .HasColumnName("dealership_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("DealershipId", "IsActive")
                        .HasDatabaseName("ix_technicians_dealership_active");

                    b.ToTable("technicians", (string)null);
                });

            modelBuilder.Entity("KeyloopScheduler.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("KeyloopScheduler.Domain.Entities.Dealership", null)
                        .WithMany()
                        .HasForeignKey("DealershipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KeyloopScheduler.Domain.Entities.ServiceBay", null)
                        .WithMany()
                        .HasForeignKey("ServiceBayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KeyloopScheduler.Domain.Entities.ServiceType", null)
                        .WithMany()
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("KeyloopScheduler.Domain.Entities.Technician", null)
                        .WithMany()
                        .HasForeignKey("TechnicianId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KeyloopScheduler.Domain.Entities.ServiceBay", b =>
                {
                    b.HasOne("KeyloopScheduler.Domain.Entities.Dealership", null)
                        .WithMany()
                        .HasForeignKey("DealershipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("KeyloopScheduler.Domain.Entities.Technician", b =>
                {
                    b.HasOne("KeyloopScheduler.Domain.Entities.Dealership", null)
                        .WithMany()
                        .HasForeignKey("DealershipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
